language: python
services:
  - docker
before_install:
  - docker build -t bobail-prediction -f cpu.Dockerfile .
script:
  - docker run bobail-prediction bash -c "pytest"
notifications:
  email:
    on_success: never